[Rvm] reuse same Python interpreter for spawned tests
Currently, the RVM test suite hard-codes the name of the Python interpreter to
be `python`, which is then looked up in the users' PATH of course.  However,
on stock OSX there is no longer a `python`, only a `python3`.  This means the
shabang is broken on OSX:

```
nathta@bcd0741cf59d Rvm % ./run_all_examples.py
env: python: No such file or directory
nathta@bcd0741cf59d Rvm %
```

If the user specifies a different interpeter manually, the test runner fails
because subprocesses spawned make the same assumption:

```
nathta@bcd0741cf59d Rvm % python3 ./run_all_examples.py
...
FileNotFoundError: [Errno 2] No such file or directory: 'python'
nathta@bcd0741cf59d Rvm %
```

This commit simply changes the subprocess interpreter to be the same as the
parent one.  I did not touch the shabang because I don't know what the right
thing to do here is: if we're expecting these tests to run in environments
without a `python3` on the path, then we've solved one problem and then created
another.